baseURL: "https://srivastava-prachi.github.io/"
title: "Prachi Srivastava"
theme: "PaperMod"

menu:
  main:
    - name: Research
      url: /research/
      weight: 1
    - name: Publications
      url: /papers/
      weight: 2
    - name: Teaching
      url: /teaching/
      weight: 3

params:
  description: "Welcome to Prachi Srivastava's academic website"
  author: "Prachi Srivastava"
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: false
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ["research", "teaching"]
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true

  profileMode:
    enabled: true
    title: "Prachi Srivastava"
    subtitle: |
     Hi! I am an Assistant Professor (W1 Junior Prof) at the <a href="https://www.awi.uni-heidelberg.de/en" target="_blank"><b>Alfred-Weber-Institute, Heidelberg University</b></a>, and Research Affiliate at the <a href="https://www.centralbank.ie/" target="_blank"><b>Central Bank of Ireland</b></a>. I hold a Ph.D. in Economics from the <a href="https://www.ucd.ie/economics/" target="_blank"><b>University College Dublin</b></a>.
     I work on topics in macroeconomics, especially expectations, uncertainty, and labor.
    imageUrl: "prachi_picture.png"
    imageWidth: 200
    imageHeight: 200
    buttons:
      - name: Research
        url: /research/
      - name: Publications
        url: /papers/
      - name: Teaching
        url: /teaching/

  socialIcons:
    - name: CV
      url: /cv.pdf
    - name: Email (Personal)
      url: mailto:prachi.jmc13@gmail.com
    - name: Email (Work)
      url: mailto:prachi.srivastava@awi.uni-heidelberg.de
    - name: Google Scholar
      url: https://scholar.google.com/citations?user=WZCkXbUAAAAJ&hl=en
    - name: GitHub
      url: https://github.com/srivastava-prachi
    - name: Twitter
      url: https://x.com/PrachiSpace9
    - name: Linkedin
      url: https://www.linkedin.com/in/prachi-srivastava95/

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
